### ISSUE TITLE
Servidor fora de serviço

### ISSUE THREAD

**Issue by lucsgtv** [GAD-DIMNT-CPTEC/SMNAMonitoringApp#4]
![image](https://github.com/user-attachments/assets/7f59967a-0e39-4db9-b38b-cc2a87919884)

Seria necessário talvez ter um versão teste com alguns dados armazenados localmente para poder ver e implementar interface.

**Comment by lucsgtv** [comment]
Fornecer outras mensagens de erro:
Ocultar endereço dos dados, sob risco de DDOS.

**Comment by cfbastarz** [comment]
Olá @lucsgtv, vou verificar com a equipe de redes do CPTEC sobre esse problema. Enquanto isso, você pode utilizar a ideia do script a seguir para obter alguns dados para uso offline:

```bash
#! /bin/bash

base_url=https://dataserver.cptec.inpe.br/dataserver_dimnt/das/carlos.bastarz/SMNAMonitoringApp/
base_path=$PWD

Dirs=(anls berror jo logs mass objeval obsm rdiag)
Arqs=(aweekbefore.txt cleanup.sh cleanup.sh.bak crontab.txt dummy_aweekbefore.txt dummy_todaym1H.txt startup.sh todaym1H.txt)

for dir in ${Dirs[@]}
do

#echo $dir
#mkdir -p $base_path/$dir

if [ $dir = anls -o $dir = rdiag ]
then

for date in $(find . -maxdepth 1 -type d -name "2*" | sort | tail -3)
do

wget -e robots=off --recursive --no-parent $base_url/$dir/$date

done

else

wget -e robots=off --recursive --no-parent $base_url/$dir

fi

done

exit 0
```

**Comment by lucsgtv** [comment]
The debug version it's ready.
https://github.com/lucsgtv/SMNAMonitoringApp-DebugVersion
